language: node_js
node_js:
- 4
- 5
- 6
- stable
after_success:
- ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  email: yuhta.nakajima@gmail.com
  api_key:
    secure: w5PJtr+mBAMOAdJiuFHNykSTUWz3u7UrDgcD4MmFQJOttFazm3/DYDu+MRghtSqi/ngmuW4wgYdwfLA1Wlby9pPzsxYC1Ga7mOXlfSSY2sNM61wcauLNkxbpTU0ghVN0hXwZ3uRujbRHy+U8JR8Z2ZZJ7gDaIiaf2uybbfiGw+IlUAIa5zZ3HsbyiMHvdh0grVHVsZiMWzzewWGu3q3Z7pQLZ9JUqXz7o7xQkLRYFLznGt8qhrlW4lmHsBFvh41pxWEOOcZBMWuSfP9lF37vOoYNc5RaQC5Qvhra2fkQX7V3r1SuXYWclN0AbD5ZTrv5rB0VUYWmistjh79YwbYSNi/GK8trXRIT1WTfxfD+0ds5aON63tKOEbbK43xAHHuSpa2FI5lkcHL8wGxs4TDoxvepPg8gZ5AG7H44vIBAXG7OA7CNgX9ZUL2uHsdyVsW7UlUHunGfFU4HYEFfFIGwjnFmEPk241Cg6NWrk9Ql1orDuAie3sDKjO5yTVsLJtfhe+rF8bbj4fpU4UE195FpfHsrjB1FzBa/T154SF5Lv8iU/MWQlhSet+YL8cgfd3prA5si31jow8BU3EhvGFYHylyuHvZ4w1b0vsdDEcE/7X3BMsXwfzCY2VY8TFPSV3Ksz49tWX87Gt0zZjKxslR1IB+YiLnx8SX70AMkRCY0UYU=
  on:
    tags: true
    repo: ynakajima/posthtml-comment-after
