language: node_js
node_js:
- 4
- 5
- 6
- stable
after_success:
- ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  email: yuhta.nakajima@gmail.com
  api_key:
    secure: ejWTwrJ/IQHNQBxnXDKpVi9l1qUMDC0I0jcjG3oRSN0/gIhgBSs4vA6sAJx4aRz0tg5K0XtJXg2bDkqXxCz7u4WgX34UxmLdbnL1JUEHaOTsMd1dBMrvGRBmj+X/FLCzb2a02kbVkh9O6BpyqAf9QJY6niCmgoIaJU8vxUYfY9+CcxuhXJD45ewBVy+JBvekleTzqreblT5rdsfZTot1y1bgOJ6eNyi+uBdFpv+qm0U+Rusmt4JFPCrPSKZfJs0rq9zaSDw/B61i6+S4rw71cEjavYiNL+tV5wyBbRWj+CoW6hBoGn5ERpD1lAXhxKSY/kPHZ81a5ff6b2fk+hQjLa3daZIFRAAWbR4dLp4kiiUusqsS8ZIc3/kRsolCVn2bbmG+KbWCqi7lZlrrW5bLMoGSiWKsH0LFFDmccjjiMbxnRpUVPV0zIMz63i+t10+3VvknNLofhw+9V3+FW8ycLp4BEoshgbmHH4w1RzGHoPsvfrPRKa9ZdJcCc0kD4XZjECyaZ//RkRjnro47/PteKLKhC0fJ1GnBMpQPaao7zEEd/Y03KMobHrM/m+wFslK8uogtjpylTBOjXyWhyqfGzaCbhCofPzs9EpAM1xQLDKHQuMjApPB7qQwPjj3Ewpm/jbdKaf4y2fu8OOqNZ/jL9WT0R/IbkDrJgQVwgVWyYcQ=
  on:
    tags: true
    repo: ynakajima/posthtml-comment-after
